"""
GBM latency surrogate predictor.

Trained on synthetic (architecture → latency) data generated by
running real ONNX Runtime microbenchmarks on the current CPU.
Replaces 80%+ of full latency measurements during NAS search.

Training data: ~5K (arch_features, measured_latency_ms) pairs
generated by build_latency_dataset.py.

Features per architecture:
  n_layers, total_params, total_flops,
  max_width, min_width, mean_width,
  depth_width_ratio, input_size
"""
from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Sequence

import numpy as np

_DEFAULT_MODEL_PATH = Path(__file__).parent.parent.parent / "results" / "latency_predictor.json"


class LatencyPredictor:
    """
    Lightweight GBM latency surrogate.

    If a trained model file is available, uses it.
    Falls back to a simple analytical estimate (params × constant).
    """

    def __init__(self, model_path: Path | str | None = None):
        self._gbm = None
        self._fallback_coeff: float = 0.0  # ns per param (fallback)

        path = Path(model_path) if model_path else _DEFAULT_MODEL_PATH
        if path.exists():
            self._load(path)

    def predict_ms(self, arch_features: dict) -> float:
        """
        Predict p50 latency in ms for an architecture.

        arch_features keys:
            n_layers, total_params, total_flops,
            max_width, min_width, mean_width, input_size
        """
        x = self._featurize(arch_features)
        if self._gbm is not None:
            return float(self._gbm_predict(x))
        return self._fallback(arch_features)

    def is_trained(self) -> bool:
        return self._gbm is not None

    # ── Training ──────────────────────────────────────────────────────────────

    def train(self, records: list[dict], save_path: Path | str | None = None) -> dict:
        """
        Train GBM on a list of {"features": dict, "latency_ms": float} records.
        Returns training stats.
        """
        try:
            import lightgbm as lgb
        except ImportError:
            raise ImportError("lightgbm required for training: pip install lightgbm")

        X = np.array([self._featurize(r["features"]) for r in records])
        y = np.array([r["latency_ms"] for r in records])

        # 80/20 split
        n = len(X)
        idx = np.random.RandomState(42).permutation(n)
        split = int(n * 0.8)
        X_tr, X_val = X[idx[:split]], X[idx[split:]]
        y_tr, y_val = y[idx[:split]], y[idx[split:]]

        params = {
            "objective": "regression",
            "metric": "rmse",
            "num_leaves": 31,
            "learning_rate": 0.05,
            "feature_fraction": 0.9,
            "n_estimators": 300,
            "verbose": -1,
        }
        model = lgb.LGBMRegressor(**params)
        model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)],
                  callbacks=[lgb.early_stopping(30, verbose=False),
                             lgb.log_evaluation(-1)])

        preds = model.predict(X_val)
        mape = float(np.mean(np.abs(preds - y_val) / (y_val + 1e-6)) * 100)
        r2 = float(1 - np.sum((preds - y_val)**2) / (np.sum((y_val - y_val.mean())**2) + 1e-9))

        # Serialize: store trees as JSON (no sklearn pickle dependency)
        self._gbm = model
        self._fallback_coeff = float(np.median(y / (X[:, 1] + 1)))  # params column

        if save_path is not None:
            self._save(Path(save_path), model)

        return {"mape_pct": round(mape, 2), "r2": round(r2, 4),
                "n_train": split, "n_val": n - split}

    # ── Private ───────────────────────────────────────────────────────────────

    def _featurize(self, f: dict) -> list[float]:
        widths = f.get("widths", [f.get("mean_width", 128)] * f.get("n_layers", 1))
        return [
            float(f.get("n_layers", len(widths))),
            float(f.get("total_params", sum(widths))),
            float(f.get("total_flops", sum(widths))),
            float(max(widths)),
            float(min(widths)),
            float(sum(widths) / len(widths)),
            float(len(widths) / (max(widths) + 1)),
            float(f.get("input_size", 784)),
        ]

    def _fallback(self, f: dict) -> float:
        params = f.get("total_params", 100_000)
        coeff = self._fallback_coeff if self._fallback_coeff > 0 else 1e-5
        return float(params * coeff)

    def _gbm_predict(self, x: list[float]) -> float:
        return float(self._gbm.predict(np.array([x]))[0])

    def _save(self, path: Path, model) -> None:
        path.parent.mkdir(exist_ok=True)
        model.booster_.save_model(str(path.with_suffix(".lgb")))
        meta = {"fallback_coeff": self._fallback_coeff,
                "model_file": str(path.with_suffix(".lgb"))}
        path.write_text(json.dumps(meta, indent=2), encoding="utf-8")

    def _load(self, path: Path) -> None:
        try:
            import lightgbm as lgb
            meta = json.loads(path.read_text(encoding="utf-8"))
            lgb_file = Path(meta.get("model_file", path.with_suffix(".lgb")))
            if lgb_file.exists():
                self._gbm = lgb.Booster(model_file=str(lgb_file))
                self._fallback_coeff = float(meta.get("fallback_coeff", 0.0))
        except Exception:
            pass  # degrade gracefully to fallback
